- name: restart sshd
  systemd:
    name: sshd
    state: restarted
  listen: "restart sshd"

- name: edit host config file
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_host }} {{ hostname }}"
  listen: "edit host config file"

